# Dependencies
markdown: kramdown
highlighter: rouge

# Gems
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-paginate

# Settings
exclude:
  [
    CNAME,
    README.md,
    LICENSE.md,
    .gitignore,
    package.json,
    yarn.lock,
    _js,
    _scss,
    _images,
    gulpfile.js,
    gulpconfig.js,
    node_modules,
    gemfile,
    Gemfile.lock,
    lint-staged.config.js,
    prettier.config.js,
  ]
permalink: /:title/
compress_html:
  clippings: all
  comments: all
dark_theme: false

# Site meta
title: 红楼梦诗词
# tagline: 'A one-page, two-column Jekyll theme.'
# keywords: 'connor, baer, bear, designer, developer, design, code, jekyll, spring'
description: '曹雪芹'
# url: https://zh.wikipedia.org/zh-tw/%E6%9B%B9%E9%9B%AA%E8%8A%B9
baseurl: ''
assets: '/assets'
images: '/images'
logo: /ass/ets/apple-icon-144x144.png
youtube: Stevmo Schwiney
# twitter:
#   username: 
# facebook:
#   app_id: 


author:
  name: Stevmo Schiney
  url: 
  email: 
  twitter: 
  youtube: Stevmo Schwiney

social:
  youtube: Stevmo Schwiney
  twitter:
  instagram: 
  github: 
  medium:

version: 4.0.0

# github:
#   repo: https://github.com/connor-baer/spring

# Integrations
# typekit:              fcv7rfe

google_fonts:
  PT Sans: 400, 700
  PT Serif: 400, 700
  Playfair Display: 400


# Content
excerpt_separator: <!--break-->

# navigation:
#   Medium: 
#   Twitter: 
#   Github: 
#
# paginate                     : 2
# paginate_path                : '/page-:num/'
# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: www-hubl-ml
