# Dependencies
markdown: kramdown
highlighter: rouge

# Gems
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-redirect-from
  - jekyll-seo-tag

# Settings
exclude:
  [
    CNAME,
    README.md,
    LICENSE.md,
    .gitignore,
    package.json,
    yarn.lock,
    _js,
    _scss,
    _images,
    gulpfile.js,
    gulpconfig.js,
    node_modules,
    gemfile,
    Gemfile.lock,
    lint-staged.config.js,
    prettier.config.js,
  ]
permalink: /:title/
compress_html:
  clippings: all
  comments: all
dark_theme: false

# Site meta
title: 红楼梦诗词
# tagline: 'A one-page, two-column Jekyll theme.'
# keywords: 'connor, baer, bear, designer, developer, design, code, jekyll, spring'
description: '曹雪芹'
# url: https://connor-baer.github.io
baseurl: ''
assets: '/assets'
images: '/images'
logo: /ass/ets/apple-icon-144x144.png
youtube: Stevmo Schwiney
# twitter:
#   username: 
# facebook:
#   app_id: 

google_analytics_key: UA-37412525-4
google_site_verification: Z-pc_HPc4XNBz8xg1fgtxO2MSIYLirZc2jWTNq0bJyM

author:
  name: Stevmo Schiney
  url: 
  email: 
  twitter: 
  youtube: Stevmo Schwiney

social:
  youtube: Stevmo Schwiney
  twitter:
  instagram: 
  github: 
  medium:

version: 4.0.0

# github:
#   repo: https://github.com/connor-baer/spring

# Integrations
# typekit:              fcv7rfe

google_fonts:
  PT Sans: 400, 700
  PT Serif: 400, 700
  Playfair Display: 400

google_analytics_key: UA-94021817-2
google_site_verification: Z-pc_HPc4XNBz8xg1fgtxO2MSIYLirZc2jWTNq0bJyM

# Content
excerpt_separator: <!-- Read more -->

# navigation:
#   Medium: 
#   Twitter: 
#   Github: 
